puts "The students in my cohort at Makers Academy"
puts "-------------"
puts "Nicki"
puts "Chris"
puts "Georgio"
puts "JB"
puts "Lara"
puts "James"
print "Overall we have "
print 9
puts " great students"